### ISSUE TITLE
GitHub Pages build failed

### ISSUE THREAD

**Issue by HactarCE** [kpreid/cubes#72]
The [GH Pages build from two months ago](https://github.com/kpreid/cubes/runs/917244314) failed, so https://kpreid.github.io/cubes/cubes.html still has an older version of the code which errors with `TypeError: context.listener.setVelocity is not a function`.

**Comment by kpreid** [comment]
Fixed in 41411c3aabff3d3750351b4054e0d5c76e3060ba.
The code required no real changes, but the GitHub Pages build failed because it wasn't a fan of the contents of the `deps/jasmine` submodule, so I trimmed it down by vendoring (copying the actual needed files into this repository).
